### ISSUE TITLE
scsc

### ISSUE THREAD

**Issue by kevinchua6** [kevinchua6/bugreporting#3]
csc

**Comment by yourally2** [comment]
# Team's Response

Cannot be reproduced with non-image file. For example, we use the command edit 1 i/john_doe.txt, the application will feedback the user that the file is non-image and the profile picture will not be updated.
image.png
# Duplicate status (if any):

--

**Comment by yourally2** [comment]
# Team's Response
Should be Very Low. Does not make any sense.


## Duplicate status (if any):
--

**Comment by yourally2** [comment]
# Team's Response
I assign myself!


## Duplicate status (if any):
--
